### ISSUE TITLE
ArgumentOutOfRangeException for BGSDKSettings.cs

### ISSUE THREAD

**Issue by dblatner** [heathen-engineering/BGSDK-Foundation#2] opened 2021-04-22 17:43 UTC
When trying to use the Sample scene with Unity 2019.4.* , the BGSDKSettings.cs throws an error and thus the SDK can not be tested.

Please check this screenshot:
![image](https://user-images.githubusercontent.com/3613737/115761548-bc0e1100-a3a2-11eb-8f97-6b70632c701d.png)

**Comment by JamesMcGhee** [comment] 2021-04-24 10:58
These are messages from Uinty's UIElements which is the API used for the inspector / editor UI.

Not seeing the same results on Unity 2019.4 in my inital tests, I assume you have the Settings object selected and this is the errors your getting.

**Comment by JamesMcGhee** [comment] 2021-04-24 11:14
On closer inspection I was able to get Unity to throw this message by simply selecting any UIELements template control. This appears to be an issue either with Unity UIElements directly or version issues between the UIElements used to create the inspector and the current version from Unity. 

I will continue to investigate and let you know when we have a workaround.

**Comment by JamesMcGhee** [comment] 2021-04-24 11:56
We have isolated the root cause of the issue.

Unity UI Elements references images and other assets via string path. These paths break under well really any situation at all that would cause the path to be different than it was at dev time.
Unity UI ELements throws this null ref when it cant resolve the asset path

This means UI Elements is far to fragile to use in the asset and we will be removing any path references we have in the short term and in the long term will work with Unity to find a bettter solution for references or simply move off the UI Elements framework.

I will post again once the fix has been uploaded

**Comment by JamesMcGhee** [comment] 2021-04-24 14:04
Corrected in the latest update

Update not pushed to release just yet but you can grab it via package manager

**Closed by JamesMcGhee** 2021-04-24 14:04 UTC
